# Generated by Django 5.2.12 on 2026-03-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', 'position', 'id']},
        ),
    ]
