# Generated by Django 5.2.12 on 2026-03-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', 'is_done', 'id']},
        ),
    ]
